language: java

sudo: false

env:
  global:
    - "AWS_ACCESS_KEY_ID=AKIAJQUIQIL3XTBHT3DA"
    # our AWS_SECRET_ACCESS_KEY follows
    - secure: "C5Y0miWN35KMpWNT/r3n31J/JjUJA6a9I/w5DUkm5xFLv1oStOvNL9KykRQIL4+9yW7hYUcGOI0iP9ZjtbxRouP5//PCjhlgzIGJ3WImVZq4fLNl3sq3DYtgZJT5rUeXn8r8cKE3/sloEbcbz7dFNXmbSACuaZ0/T3IZpgP/Yrs="
    - secure: jiXXdeeqDRf2NoilQRWlUn6nYATL0VRmNA38J0M0I23/+4yPjahHALzHJdL7ztsPFR9rO9r1X3T5f7+KQrH6r+O95Aqz6tqqL7qD/Z8xrDjcYcb11DWdKGOrrD3b6FtrCf+LfUdeOIdOh4oZVFhnhvtaqxbbK4eVbCfsSkwSZMC9Rq5q5BUpcQ/sZ/Kor+INObGqbQyLKetKKn9hozFZ/DLwa06qkDxymmUVs2lV28HTeyeyfltYNYX6u4k2Q/xXyiG1qDybNlwJEChKGzMq15v45/7Lp9Ml77F8gjZZ+b1QAaU/0xmGo/5FM20aR4XpWTEV2gfOwhmleEa+ZJrIt3TgOmrktAHZAjAURmJ4zXxVDoELOlPfYS2cmx/4GKE3lH23JnjxQtAM4dhlVXIrHvKenucNWKKRR5/G0vw80ALicgxr6IOUHtI1TZtDTs3E7KwWa2+PFKQ/Hk4xiwNYih2n9hcS7BEZdZXW+PA1pLbJVyvB4v1cJVtg7x+DnhAA/7HY2ilT85ez+wdsXuFIHK5Vw9lPNbkugW4fNspsHsCOS5trTgK456iDDOnDEOVYwRlQ6aThyOfafIABWmpu5/55MPSakPPG4QEGa6VRUwY9Kdo5UewAHa4zUjaR06Vh5QGT+CpmpaomqVwzXgAT0vNisUSirWXh2vuLxBO2jxo=
    - secure: m5OxO+Bcw/pBOAFkCTEPAoqCwGXcpjAz6kQRikZCB3UI2QWfx/be8TZa9PhCskgcLRGemlCpQ1zVFDc9sMkJDn+B26qkS60VgM5B1dt/iMrwPYh1aMAh6g9+mMZe2sm910aHmr5eOTnNqGZXHN0De4FBDmOoVYoQMBOae4hvmo4kIat3IgOID4O8RwufWXgaWgZEXWgIz5Acj1Zlh6b7LDPv0OLOj+jz8ROdagBTKRpsAFQBzSCi8q5a+loIhHhZe+iBhWSUYUfiwQOGaGQ4a0Nka457VicnOs3IaAMVnMmu8ZVegF7xQd8Che96LzFGujZHMujHzAco8w+JVuH4jv5daIrGanGDb/kPggpYHyKmjOY4iwJiS7++ByBkSlZD40qWsD5g5TNnyvQx61h08TBTEREq5T+imGTGIh+E+AEausA/pZLx5XFURhw7YG+wXTureq9qNKcEq/z2mJuDkd1AQ2KTi5/L67P14LPKgSm/fXeb0zSWMVqQsiaF4QuMoE3PtsrgDtHSnBZW74puEn0TBo8Id0yf++sXzuUdsQ5wo1lrhfo7MHNvogi9sjqrWu+bhDXPJxnHyNdmnQUKyfU5RNqjeWjYonpAqZeaqYEuDDkgK16YnbQWV+PVto+v5x/aZo53+algefGSD2hszHNpvzlS5ETkBP9hXjVjJR4=

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -f  $HOME/.gradle/caches/jars-2/jars-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  apt: true
  directories:
  - lib/
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install: echo -e "org.gradle.parallel = true\norg.gradle.jvmargs=-Xms256m -Xmx1024m\norg.gradle.configureondemand=true\ntasks.withType(Test) {\n maxParallelForks = Runtime.runtime.availableProcessors()\n}" > gradle.properties
install: "./gradlew jar"

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

before_deploy:
  - "./gradlew javadoc ; true"
  - "pip install --user awscli"
  - "./gradlew copyRuntimeLib"
deploy:
  - provider: script
    script: ~/.local/bin/aws s3 sync --region=us-east-1 --cache-control "public, max-age=86400" --content-encoding utf-8 --delete build/docs/javadoc/ s3://website-javadoc.freenetproject.org
    skip_cleanup: true
    on:
      branch: next
      jdk: openjdk8
  - provider: script
    script: ./gradlew -x test publish
    skip_cleanup: true
    on:
      tags: true
      jdk: openjdk8
  - provider: releases
    skip_cleanup: true
    api_key:
      - secure: CDYRFrmkAOdn4QJVww6/pziDVdZ67fvRsLOKbilao/oRdP0uvsYS+OfX+Spu/Y0qCY0xSehvqgUoD8KoFqWuhos3iF4N515S5WNuiqOao7Ac2vBCt0ZMJy7MktyE5mYOD1Paf891n6Z+eILWGI54GGEau3JPes0G9jdMphW4ma8=
    prerelease: true
    file: build/output/*jar
    file_glob: true
    on:
      tags: true
      jdk: openjdk8
